# Generated by Django 4.2.4 on 2023-08-09 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_gasto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_ingreso', models.IntegerField()),
                ('fuente_ingreso', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ahorros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_ahorro', models.IntegerField()),
                ('fecha_ini_ahorro', models.DateField()),
                ('fecha_fin_ahorro', models.DateField()),
                ('ingresos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test1.ingresos')),
            ],
        ),
    ]
