# Generated by Django 4.2.4 on 2023-08-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='fuente',
            field=models.CharField(max_length=40),
        ),
    ]
