# Generated by Django 4.2.4 on 2023-08-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test1", "0002_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="contrasena",
            field=models.CharField(default="admin", max_length=50),
        ),
        migrations.AddField(
            model_name="usuario",
            name="correo",
            field=models.EmailField(default="admin", max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="nombre",
            field=models.CharField(default="admin", max_length=55),
        ),
    ]
