# Generated by Django 4.2.4 on 2023-08-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_alter_transacciones_fuente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacciones',
            name='fk_categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
