# Generated by Django 4.2.4 on 2023-08-09 20:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test1", "0003_usuario_contrasena_usuario_correo_usuario_nombre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="contrasena",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="correo",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="nombre",
        ),
    ]
