# Generated by Django 4.2.4 on 2023-08-16 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_remove_transacciones_fk_categoria_delete_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fuente_ingreso', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_categoria_gasto', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='transacciones',
            name='fk_categoria',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='test1.categoria'),
        ),
    ]
