# Generated by Django 4.2.4 on 2023-08-16 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_categoria_transacciones_fk_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente_ingreso', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria_gasto', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='fk_categoria',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='test1.clasificacion'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
