# Generated by Django 4.2.4 on 2023-08-16 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0005_clasificacion_alter_transacciones_fk_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FuenteIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fuente', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='transacciones',
            name='fuente',
        ),
        migrations.AddField(
            model_name='transacciones',
            name='fk_fuente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test1.fuenteingreso'),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='fk_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test1.categoriagasto'),
        ),
        migrations.DeleteModel(
            name='Clasificacion',
        ),
    ]
