# Generated by Django 4.2.4 on 2023-08-17 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0007_alter_cuentas_saldo_alter_transacciones_fk_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacciones',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
