# Generated by Django 4.2.4 on 2023-08-14 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0008_cuentas_transacciones_remove_ahorros_ingresos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 8, 14, 13, 42, 45, 568921)),
        ),
    ]
