# Generated by Django 4.2.4 on 2023-08-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0008_transacciones_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacciones',
            name='user',
        ),
    ]
