# Generated by Django 4.2.4 on 2023-08-14 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0009_alter_transacciones_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 8, 14, 15, 36, 26, 652607)),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='fuente',
            field=models.CharField(choices=[('hola', 'hola'), ('si', 'si')], max_length=20),
        ),
    ]
