# Generated by Django 4.2.4 on 2023-08-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test1", "0009_remove_transacciones_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
