# Generated by Django 4.2.4 on 2023-08-14 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0010_alter_transacciones_fecha_alter_transacciones_fuente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 8, 14, 16, 6, 52, 809348)),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='fuente',
            field=models.CharField(max_length=20),
        ),
    ]
