# Generated by Django 4.2.4 on 2023-08-15 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0011_alter_transacciones_fecha_alter_transacciones_fuente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 8, 15, 10, 24, 0, 569528)),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='fuente',
            field=models.CharField(max_length=50),
        ),
    ]
