# Generated by Django 4.2.4 on 2023-08-25 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test1", "0010_alter_usuario_email"),
        ("test1", "0011_alter_transacciones_fk_cuenta"),
    ]

    operations = []
