# Generated by Django 4.2.4 on 2023-08-25 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("test1", "0012_merge_20230825_1115"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuentas",
            name="fk_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
