# Generated by Django 4.2.4 on 2023-08-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0013_categoria_remove_transacciones_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='fecha',
            field=models.DateField(),
        ),
    ]
