# Generated by Django 4.2.4 on 2023-08-15 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0014_alter_transacciones_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='fk_categoria',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='test1.categoria'),
        ),
    ]
