# Generated by Django 4.2.4 on 2023-08-25 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test1", "0014_alter_usuario_groups_alter_usuario_user_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cuentas",
            name="tipo",
        ),
    ]
