# Generated by Django 4.2.4 on 2023-09-07 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("test1", "0018_categoriagasto_fk_user_fuenteingreso_fk_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriagasto",
            name="fk_user",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_superuser": False},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorias_personalizadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fuenteingreso",
            name="fk_user",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_superuser": False},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fuentes_personalizadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]

# Generated by Django 4.2.4 on 2023-09-08 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0018_categoriagasto_fk_user_fuenteingreso_fk_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriagasto',
            name='fk_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_superuser': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_personalizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fuenteingreso',
            name='fk_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_superuser': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuentes_personalizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
