# Generated by Django 4.2.4 on 2023-09-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test1", "0019_alter_categoriagasto_fk_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="test1/images"),
        ),
    ]
