# Generated by Django 4.2.4 on 2023-09-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test1", "0020_usuario_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
