# Generated by Django 4.2.4 on 2023-09-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test1", "0024_remove_usuario_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="imagen",
            field=models.ImageField(
                blank=True,
                default="static/img/icon-user.png",
                null=True,
                upload_to="images",
            ),
        ),
    ]
