# Generated by Django 4.2.4 on 2023-09-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0028_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile'),
        ),
    ]
