# Generated by Django 4.2.4 on 2023-09-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0041_alter_deudas_valor_de_interes_mensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudas',
            name='frecuencia_de_pago',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deudas',
            name='plazo_del_prestamo',
            field=models.IntegerField(blank=True, max_length=1000, null=True),
        ),
    ]
