# Generated by Django 4.2.4 on 2023-09-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0042_deudas_frecuencia_de_pago_deudas_plazo_del_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deudas',
            name='plazo_del_prestamo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
