# Generated by Django 4.2.4 on 2023-09-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0043_alter_deudas_plazo_del_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudas',
            name='valor_de_interes_fijo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='deudas',
            name='valor_de_interes_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
