# Generated by Django 4.2.4 on 2023-09-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0044_deudas_valor_de_interes_fijo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deudas',
            old_name='valor_de_interes_fijo',
            new_name='tasa_de_interes',
        ),
        migrations.RemoveField(
            model_name='deudas',
            name='valor_de_interes_mensual',
        ),
    ]
