# Generated by Django 4.2.4 on 2023-10-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0047_deudas_valor_interes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deudas',
            old_name='tasa_de_interes',
            new_name='tasa_de_interes_anual',
        ),
        migrations.RenameField(
            model_name='deudas',
            old_name='valor_interes',
            new_name='valor_interes_anual',
        ),
        migrations.AddField(
            model_name='deudas',
            name='tasa_de_interes_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='deudas',
            name='valor_interes_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
