# Generated by Django 4.2.4 on 2023-10-05 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0049_remove_deudas_valor_interes_anual_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deudas',
            old_name='Capitalizacion',
            new_name='capitalizacion',
        ),
    ]
