# Generated by Django 4.2.4 on 2023-10-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0050_rename_capitalizacion_deudas_capitalizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deudas',
            name='descripcion_deuda',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deudas',
            name='tipo_de_interes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deudas',
            name='valor_total_deuda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
