# Generated by Django 4.2.4 on 2023-10-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0052_alter_deudas_capitalizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deudas',
            name='capitalizacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
