# Generated by Django 4.2.4 on 2023-10-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0053_alter_deudas_capitalizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deudas',
            name='capitalizacion',
        ),
    ]
