# Generated by Django 4.2.4 on 2023-10-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0054_remove_deudas_capitalizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudas',
            name='dia_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
