# Generated by Django 4.2.4 on 2023-10-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0057_recordatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deudas',
            name='dia_pago',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
