# Generated by Django 4.2.5 on 2023-10-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0059_ahorro'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahorro',
            name='tipo',
            field=models.CharField(default='Mi ahorro', max_length=50),
        ),
        migrations.AlterField(
            model_name='ahorro',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
