# Generated by Django 4.2.5 on 2023-10-25 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0060_ahorro_tipo_alter_ahorro_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ahorro',
        ),
    ]
