# Generated by Django 4.2.5 on 2023-10-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0062_ahorro'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahorro',
            name='monto_a_devolver',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
