# Generated by Django 4.2.5 on 2023-10-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0063_ahorro_monto_a_devolver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ahorro',
            name='monto_a_devolver',
        ),
    ]
