# Generated by Django 4.2.5 on 2023-11-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0064_remove_ahorro_monto_a_devolver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahorro',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
